# Generated by Django 3.2.16 on 2022-12-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_auto_20220530_1731"),
        ("mainapp", "0004_coursefeedback"),
    ]

    operations = []
